name: Android Release CI

on:
  release:
    types: [published, created]

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
      - name: Set up NDK
        uses: nttld/setup-ndk@afb4c9964b521afb97c864b7d40b11e6911bd410
        with:
          ndk-version: r28c
          link-to-sdk: true
          local-cache: true
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assembleDebug
      - name: Upload fdroid artifact
        uses: actions/upload-artifact@v4
        with:
          name: Amaze-Fdroid-debug
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
      - name: Upload play artifact
        uses: actions/upload-artifact@v4
        with:
          name: Amaze-Play-debug
          path: app/build/outputs/apk/play/debug/app-play-debug.apk
