name: Android Build CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release/*'
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_spotless:
    name: Check spotless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
      - name: Set up NDK
        uses: nttld/setup-ndk@afb4c9964b521afb97c864b7d40b11e6911bd410
        with:
          ndk-version: r28c
          link-to-sdk: true
          local-cache: true
      - name: Check formatting using spotless
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: spotlessCheck --stacktrace

  build:
    name: Build debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assembledebug --stacktrace